added badges
yarexmarvin/TestGuru pull request #17
Opened 2022-11-20 07:45 UTC by yarexmarvin

2022-11-21 05:35 UTC, VidgarVii requested changes

2022-11-21 05:35 UTC, VidgarVii commented on app/assets/stylesheets/application.scss
> +
No new line at .. 
таких ошибок уже не должно быть

2022-11-21 05:35 UTC, VidgarVii commented on app/helpers/tests_helper.rb
> +  def completed?(test)
хелперы нужны чтобы упрощать верстку сайта.
Тут же происходит запрос в бд. Данные из бд во вью передаёт только контроллер запрашивая через модели

2022-11-21 05:35 UTC, VidgarVii commented on app/controllers/admin/badges_controller.rb
> +    params.require(:badge).permit(:title, :url, :rule)
Админ при создании баджа должен выбирать тип правила (Категория/лвл и пр) И параметр правила (Ид категории/лвл уровня и пр.)

2022-11-21 05:35 UTC, VidgarVii commented on app/views/admin/badges/_form.html.erb
> +    <%= form.select :rule,  options_for_select(BadgeService::RULES.collect {|rule| [rule[:title], rule[:value]]})%>
BadgeService::RULES.pluck(:title, :value)

2022-11-21 05:35 UTC, VidgarVii commented on app/views/badges/_badge.html.erb
> +
достаточно оставить 1 пустую строку в конце файла

2022-11-21 05:35 UTC, VidgarVii commented on app/views/given_badges/_given_badge.html.erb
> +<%given_badges.each do |given_badge|%>
вспоминаем урок про вью
разве так надо рендерить коллекцию?
http://rusrails.ru/layouts-and-rendering#rendering-kollektsiy

2022-11-21 05:35 UTC, VidgarVii commented on app/views/given_badges/index.html.erb
> +<% if @given_badges.size.zero? %>
@given_badges.empty?

2022-11-21 05:35 UTC, VidgarVii commented on app/services/badge_service.rb
> +    {rule_id: 1, value: 'success_at_first_try', title: 'За успешное прохождения теста с первого раза'},
м/у скобками { } оставляют пробел
`{ a: :b }`

2022-11-21 05:35 UTC, VidgarVii commented on app/services/badge_service.rb
> +
не нужный отступ

2022-11-21 05:35 UTC, VidgarVii commented on app/services/badge_service.rb
> +    {rule_id: 2, value: 'complete_category_tests', title: 'За прохождение всех тестов из категории'},
не вижу по коду, чтобы rule_id использовался

2022-11-21 05:35 UTC, VidgarVii commented on app/services/badge_service.rb
> +
такие отступы не используются. Используй рубокоп, чтобы научиться писать чистый красивый код

2022-11-21 05:35 UTC, VidgarVii commented on app/services/badge_service.rb
> +     BadgeService end
?

2022-11-21 05:35 UTC, VidgarVii commented on app/services/badge_service.rb
> +      if send("#{badge&.rule}")
не уверен что badge может быть нил

2022-11-21 05:35 UTC, VidgarVii commented on app/services/badge_service.rb
> +    @badges = Badge.all
баджей может быть очень много. Грузить сразу всю коллекцию в память не очень разумное решение

2022-11-21 05:35 UTC, VidgarVii commented on app/services/badge_service.rb
> +  end
В ДЗ заданы 3 типа правила. Но учти что система должна быть готова к масштабировании. И правил может быть сколько угодно.
Где то типы правил надо складывать без раздутия моделей и классов

2022-11-21 09:13 UTC, yarexmarvin commented on app/controllers/admin/badges_controller.rb
> +    params.require(:badge).permit(:title, :url, :rule)
> Админ при создании баджа должен выбирать тип правила (Категория/лвл и пр) И параметр правила (Ид категории/лвл уровня и пр.)

Выбор правила из существующих я реализовал

    <%= form.select :rule,  options_for_select(BadgeService::RULES.collect {|rule| [rule[:title], rule[:value]]})%>

2022-11-21 09:17 UTC, yarexmarvin commented on app/views/given_badges/_given_badge.html.erb
> +<%given_badges.each do |given_badge|%>
> 

изначально я так и делал, но почему то он настойчиво рендерит _badge.html

в то время как у меня стоит:
      <%= render @given_badges %>

2022-11-22 05:32 UTC, VidgarVii requested changes

2022-11-22 05:32 UTC, VidgarVii commented on app/assets/stylesheets/application.scss
> +
в итоге появились лишние отступы. А проблема осталось. После любого фикса, стоит проверить, что фикс работает

2022-11-22 05:32 UTC, VidgarVii commented on app/controllers/admin/badges_controller.rb
> +    params.require(:badge).permit(:title, :url, :rule)
выбор правил есть. А опции нет

2022-11-22 05:32 UTC, VidgarVii commented on app/controllers/test_passages_controller.rb
> +  before_action :check_time_left, only: %i[show update gist]
не уверен, что в этом контроллере есть экшен gist

2022-11-22 05:32 UTC, VidgarVii commented on app/controllers/test_passages_controller.rb
> +    @test_passage.created_at + @test_passage.test.timer * 60 - Time.now <= 0 ? true : false
в это реквесте должен быть код только для баджей!

2022-11-22 05:32 UTC, VidgarVii commented on app/services/badge_rules/complete_category_tests.rb
> +  end
обрати внимание что:
1.  у подобных классов одинаковый конструктор
2. Есть повторяющий код в методах
3. Все классы можно объединить по смыслу
Тут стоит задуматься о 1 наследовании, 2 модули (тем более все классы сложены в папку)

2022-11-22 05:32 UTC, VidgarVii commented on app/services/badge_service.rb
> +  ]
1. Если я правильно понимаю, то при создании баджа правило выбирает из этого списка. В таком случаи эти данные стоит положить в модель. И сделать валидацию. чтобы не попадали в базу левые значения.
2. Контекст надо хранить не в коде, а в файлах локализации

2022-11-22 05:32 UTC, VidgarVii commented on app/services/badge_service.rb
> +    Badge.all.each do |badge|
лучше используй find_each для итераций.
метод .all почти не используют. Так как если в БД окажется большое кол-во данных, то данный метод полностью заполнит оперативную память.  И сервер зависнет

2022-11-22 13:58 UTC, VidgarVii requested changes

2022-11-22 13:58 UTC, VidgarVii commented on app/models/test.rb
> +  def completed?
А как тест может понять что он завершен? Что это за параметр такой для теста, без учета юзера?
И даже имея юзера, так же не место данной логике в этом модели.
Модель должна работать только с данными из своей таблицы. 
Текущий метод нужен для проверки правил выдачи баджа. Вот стоит его написать там где и используется. Засорять модель подобной бизнес логикой не стоит. Это просто размазывание кода по классам

2022-11-22 13:58 UTC, VidgarVii commented on app/controllers/admin/badges_controller.rb
> +    params.require(:badge).permit(:title, :url, :rule)
не исправлено. Как админ будет задавать нужный уровень или категорию?

2022-11-22 13:58 UTC, VidgarVii commented on app/models/user.rb
> +  has_many :badges, through: :given_badges
не прописана условие удаление баджей при удалении юзера. Тут баг

2022-11-22 13:58 UTC, VidgarVii commented on app/services/badge_rules/complete_category_tests.rb
> +module  CompleteCategoryTests
изначально с классами был верный подход. Надо было только их положить в 1 модуль и создать наследника. Это придаст чистую иерархию классов по единому смыслу. Т.е. мы берем нужные инструменты и кладём в 1 коробку. А сейчас в этой коробке какой бардак из коллекций методов.
Нужны объекты. А для объектов нужны классы. Это ООП!

2022-11-22 13:58 UTC, VidgarVii commented on app/services/badge_rules_service.rb
> +require_relative './badge_rules/success_at_first_try'
если нет ошибок в называниях классов, модулей и файлов то рельса сама верно подключает все нужные файлы. 
require_relative не используется

2022-11-22 13:58 UTC, VidgarVii commented on app/services/badge_rules/success_at_first_try.rb
> +  def success_at_first_try
предикатные методы должны иметь знак вопроса в названии

2022-11-22 13:58 UTC, VidgarVii commented on app/services/badge_rules/complete_level_tests.rb
> +module CompleteLevelTests
аа. так это разные модули... Если честно это еще хуже. Верни классы) надо работать с объектами

2022-11-23 05:23 UTC, VidgarVii requested changes

2022-11-23 05:23 UTC, VidgarVii commented on app/controllers/tests_controller.rb
> +    @completed_tests = TestPassage.all.filter { |passage| passage.completed? }.pluck(:test_id)
используй sql запросы, скоупы и средства ресльы. И будет код чище и проще
TestPassage.completed..pluck(:test_id)

2022-11-23 05:23 UTC, VidgarVii commented on app/controllers/admin/badges_controller.rb
> +    params.require(:badge).permit(:title, :url, :rule)
не исправлено.

2022-11-23 05:23 UTC, VidgarVii commented on app/services/badge_rules_service.rb
> +
тут бардак с отступами.

2022-11-23 05:23 UTC, VidgarVii commented on app/services/badge_service.rb
> +  }
freeze

2022-11-23 05:23 UTC, VidgarVii commented on app/services/complete_category_tests.rb
> +    return false
в конце метода retrun не пишут. Метод и так вернёт результат последней строки метода

2022-11-23 05:23 UTC, VidgarVii commented on app/services/complete_category_tests.rb
> +    return false
условное вырожение и так будет возвращать true/false
return тут вообще лишние

2022-11-23 11:10 UTC, merged