Задание по основам Rails-моделей
yarexmarvin/TestGuru pull request #2
Opened 2022-10-22 07:53 UTC by yarexmarvin

2022-10-23 07:11 UTC, VidgarVii requested changes

2022-10-23 07:11 UTC, VidgarVii commented on app/models/answer.rb
> +  belongs_to :question
ассоциации позже будут в курсе
пока лучше убери их из моделей, чтобы они не отвлекали
нам на данном этапе внешних ключей в таблицах вполне достаточно ближайшие пару уроков нужно будет ручками конструировать запросы, чтобы лучше понять, как ассоциации работают, а потом уже будем использовать ассоциации

2022-10-23 07:11 UTC, VidgarVii commented on db/migrate/20221022071502_create_tests.rb
> +
для теста нам еще понадобиться автор. Это юзер который создал тест. Но при этом по названию колонки должно быть понятно, что речь идёт именно об авторе теста. Предлагаю это сделать в текущем ПР.

2022-10-23 07:11 UTC, VidgarVii commented on db/migrate/20221022072719_create_answers.rb
> +      t.references :user, null: false, foreign_key: true
ответ принадлежит только вопросу

2022-10-23 07:11 UTC, VidgarVii commented on db/migrate/20221022073920_add_test_title_null_constraint.rb
> +    change_column_null(:tests, :title, false)
не стоит добавлять отдельные миграции для изменения полей в одном ПР. Миграции всегда являются опасным местом в ПО. Так как меняют схему базы. И всегда стараются минимизировать кол-во миграций.
В этом ДЗ надо создать 5 моделей и 5 таблиц. Значит у тебя должно быть 5 миграций. Прописывай все нужные опции полям сразу. Все остальные миграции являются обычным оверхедом

Пример
```
t.string :title, null: false 
```
Большое кол-во миграций увеличивает время развёртывания ПО. Так же миграция является местом риска, так как может сломать существующую базу. Еще они имеют свойство протухать и быть не актуальными или не рабочими. По этому всегда стараются минимизировать кол-во миграций.

2022-10-23 07:11 UTC, VidgarVii commented on db/schema.rb
> +    t.boolean "correct", default: false
для логических полей рекомендуется запрещать `null`
тогда в базе будут возможны строго два значения `true` или `false` вместо трех (`null/true/false`)

2022-10-23 08:16 UTC, yarexmarvin commented on app/models/answer.rb
> +  belongs_to :question
> ассоциации позже будут в курсе пока лучше убери их из моделей, чтобы они не отвлекали нам на данном этапе внешних ключей в таблицах вполне достаточно ближайшие пару уроков нужно будет ручками конструировать запросы, чтобы лучше понять, как ассоциации работают, а потом уже будем использовать ассоциации

убрал

2022-10-23 08:17 UTC, yarexmarvin commented on db/migrate/20221022071502_create_tests.rb
> +
> для теста нам еще понадобиться автор. Это юзер который создал тест. Но при этом по названию колонки должно быть понятно, что речь идёт именно об авторе теста. Предлагаю это сделать в текущем ПР.

добавил поле type для определения типа пользователя

2022-10-23 08:17 UTC, yarexmarvin commented on db/migrate/20221022072719_create_answers.rb
> +      t.references :user, null: false, foreign_key: true
> ответ принадлежит только вопросу

исправил

2022-10-23 08:17 UTC, yarexmarvin commented on db/migrate/20221022073920_add_test_title_null_constraint.rb
> +    change_column_null(:tests, :title, false)
> не стоит добавлять отдельные миграции для изменения полей в одном ПР. Миграции всегда являются опасным местом в ПО. Так как меняют схему базы. И всегда стараются минимизировать кол-во миграций. В этом ДЗ надо создать 5 моделей и 5 таблиц. Значит у тебя должно быть 5 миграций. Прописывай все нужные опции полям сразу. Все остальные миграции являются обычным оверхедом
> 
> Пример
> 
> ```
> t.string :title, null: false 
> ```
> 
> Большое кол-во миграций увеличивает время развёртывания ПО. Так же миграция является местом риска, так как может сломать существующую базу. Еще они имеют свойство протухать и быть не актуальными или не рабочими. По этому всегда стараются минимизировать кол-во миграций.

сделал

2022-10-23 08:17 UTC, yarexmarvin commented on db/schema.rb
> +    t.boolean "correct", default: false
> для логических полей рекомендуется запрещать `null` тогда в базе будут возможны строго два значения `true` или `false` вместо трех (`null/true/false`)

исправил

2022-10-24 03:57 UTC, VidgarVii requested changes

2022-10-24 03:57 UTC, VidgarVii commented on db/migrate/20221023075832_create_questions.rb
> +      t.integer :test_id, null: false
нужны не просто поля, а поля с [внешними ключами](https://en.wikipedia.org/wiki/Foreign_key)
Пример
```
t.references :test, null: false, foreign_key: true
```

2022-10-24 03:57 UTC, VidgarVii commented on db/migrate/20221023080608_create_tests.rb
> +
для теста нам еще понадобиться автор. Это юзер который создал тест. Но при этом по названию колонки должно быть понятно, что речь идёт именно об авторе теста. Предлагаю это сделать в текущем ПР.

2022-10-24 04:25 UTC, yarexmarvin commented on db/migrate/20221023075832_create_questions.rb
> +      t.integer :test_id, null: false
> нужны не просто поля, а поля с [внешними ключами](https://en.wikipedia.org/wiki/Foreign_key) Пример
> 
> ```
> t.references :test, null: false, foreign_key: true
> ```

поправил

2022-10-24 04:41 UTC, yarexmarvin commented on db/migrate/20221023080608_create_tests.rb
> +
> для теста нам еще понадобиться автор. Это юзер который создал тест. Но при этом по названию колонки должно быть понятно, что речь идёт именно об авторе теста. Предлагаю это сделать в текущем ПР.

добавил тесту автора

2022-10-24 08:26 UTC, VidgarVii requested changes

2022-10-24 08:26 UTC, VidgarVii commented on db/migrate/20221024043756_add_author_to_tests.rb
> +    add_reference(:tests, :author, foreign_key: { to_table: :users })
как я уже писал, в рамках одного реквеста не стоит плодить новые миграции. Исправь лучше текущие, пока они не были в мержаны в мастер

2022-10-24 14:27 UTC, merged